# Generated by Django 5.0.3 on 2024-04-06 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news_service", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newspost",
            name="content",
            field=models.TextField(blank=True, max_length=1500),
        ),
        migrations.AlterField(
            model_name="newspost",
            name="image_link",
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name="newspost",
            name="title",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
