# Generated by Django 5.0.3 on 2024-04-09 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news_service", "0002_alter_newspost_content_alter_newspost_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="newspost",
            name="tag",
        ),
        migrations.DeleteModel(
            name="Tag",
        ),
    ]
